id: I244E774B
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 16:03:21.583272
last_modified: 2023-02-08 16:03:21.583428
source_metadata:
  title: 'Vasubandhu: Triṃśikāvijñapti'
  language: bo
bases:
  263B:
    base_file: 263B.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
